# Generated by Django 2.0.3 on 2018-04-02 16:47

from django.db import migrations, models
import workouts.models


class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0003_workout_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='workout',
            name='img',
            field=models.FileField(
                default=None, upload_to=workouts.models.workout_dir_path),
        ),
    ]
