# Generated by Django 2.0.3 on 2018-04-03 02:25

from django.db import migrations, models
import workouts.models


class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0004_workout_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workout',
            name='img',
            field=models.ImageField(default=None, upload_to=workouts.models.workout_dir_path),
        ),
    ]
